jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: Prepare Git Variables
        run: |
          git config --global author.email ${{ github.actor }}@users.noreply.github.com
          git config --global author.name ${{ github.actor }}
          git config --global committer.email noreply@github.com
          git config --global committer.name GitHub
      - name: Update hooks
        id: update_hooks
        run: |
          pre-commit autoupdate
          if [[ -z "$(git status --porcelain)" ]];
          then
            echo ::set-output name=changed::false
          else
            echo ::set-output name=changed::true
          fi
      - name: Commit hook changes
        if: steps.update_hooks.outputs.changed
        run: git commit -m "Update pre-commit hooks"
      - name: Run hooks
        id: run_hooks
        run: pre-commit run --all-files
        continue-on-error: true
      - name: Check if there are changes
        id: changes
        if: steps.run_hooks.outcome == 'failure'
        run: |
          if [[ -z "$(git status --porcelain)" ]];
          then
            echo ::set-output name=changed::false
          else
            echo ::set-output name=changed::true
          fi
      - name: Commit changes
        if: steps.changes.outputs.changed
        run: git commit -a
      - uses: peter-evans/create-pull-request@v3
        with:
          branch: update/pre-commit-hooks
          title: Update pre-commit hooks
          commit-message: "Update pre-commit hooks"
          body: Update versions of pre-commit hooks to the latest version.
name: 'Update pre-commit hooks'
on:
  workflow_call:
